---
driver:
  # name: docker
  # use_sudo: false
  # provision_command:
  #   - apt-get install -y curl wget net-tools
  name: vagrant
  customize:
    memory: 1024
    cpus: 4

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: 'test/integration/encrypted_data_bag_secret'

platforms:
  - name: boxcutter/debian8
  - name: boxcutter/ubuntu1404
  - name: boxcutter/ubuntu1604
  - name: boxcutter/ubuntu1610

suites:
  - name: default
    run_list:
      - 'recipe[np-workstation]'
    attributes:
