---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 4

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: 'test/integration/encrypted_data_bag_secret'

platforms:
  - name: debian-8.4
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - 'recipe[np-workstation]'
    attributes:
      virtualbox:
        version: 5.0
