language: ruby
sudo: false
rvm:
  - 2.3.1
cache:
  bundler: true
  directories:
    - .chefdk

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

services:
  - docker

script:
  - bundle exec rspec --color
  # - bundle exec kitchen create -c8
  # - bundle exec kitchen converge -c8
  # - bundle exec kitchen verify
