source 'https://rubygems.org'

gem 'berkshelf'
gem 'chefspec'
gem 'cookstyle'
gem 'docker-api'
gem 'fauxhai'
gem 'kitchen-docker'
gem 'kitchen-inspec'
gem 'kitchen-sync'
gem 'mixlib-install', git: 'https://gitlab.com/cinc-project/mixlib-install.git', branch: 'stable/cinc'
gem 'rubocop'
gem 'rspec'
gem 'test-kitchen'
