source 'https://rubygems.org'

gem 'kitchen-inspec'
gem 'kitchen-sync'
gem 'kitchen-vagrant'
gem 'kitchen-docker'
gem 'mixlib-install', git: 'https://gitlab.com/cinc-project/upstream/mixlib-install.git', branch: 'stable/cinc'
gem 'test-kitchen'
gem 'berkshelf'
gem 'rake'
gem 'cookstyle'
gem 'chefspec'
