name 'np-workstation'
maintainer 'Nick Pegg'
maintainer_email 'nick@nickpegg.com'
license 'MIT'
description 'Sets up a workstation the way I like it'
long_description 'Sets up a workstation the way I like it'
version '0.2.3'

depends 'apt'
depends 'chrome'
depends 'docker', '= 2.9.5'

supports 'debian', '~> 8.0'
supports 'ubuntu', '= 14.04'
supports 'ubuntu', '= 16.04'
