name 'np-workstation'
maintainer 'Nick Pegg'
maintainer_email 'nick@nickpegg.com'
license 'all_rights'
description 'Sets up a workstation'
long_description 'Sets up a workstation'
version '0.1.9'

depends 'apt'
depends 'chef-dk'
depends 'chrome'
depends 'virtualbox'

supports 'debian', '~> 8.0'
supports 'ubuntu', '= 14.04'
supports 'ubuntu', '= 16.04'
