name: Kitchen tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - uses: leleliu008/github-actions-vagrant@v1
        with:
          mem: 1024

      - name: install gems
        run: bundle install

      - name: Run Kitchen tests
        run: bundle exec kitchen test
