name: test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

env:
  KITCHEN_YAML: kitchen.docker.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install Chef
        uses: actionshub/chef-install@main
        with:
          omnitruckUrl: https://omnitruck.cinc.sh/install.sh
      - name: Create
        run: bundle exec kitchen create -c4
      - name: Converge
        run: bundle exec kitchen converge
      - name: Verify
        run: bundle exec kitchen verify
