name: Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  kitchen:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - arch-latest
          - ubuntu-2004
        suite:
          - default
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Test
        run: bundle exec kitchen test --color ${{ matrix.suite }}-${{ matrix.os }}
  style_and_unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Cookstyle
        run: bundle exec cookstyle
      - name: RSpec
        run: bundle exec rspec
